# Generated by Django 2.2 on 2020-09-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание')),
                ('category', models.CharField(choices=[('other', 'Разное'), ('food', 'Еда'), ('tech', 'Бытовая техника'), ('tools', 'Инструменты'), ('toys', 'Игрушки')], default='other', max_length=20, verbose_name='Категория')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='user_pics', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
                'permissions': [('can_have_piece_of_pizza', 'Может съесть кусочек пиццы')],
            },
        ),
    ]
